import {
  AlarmRounded,
  BadgeRounded,
  BabyChangingStationRounded,
  ChecklistRounded,
  ChildCareRounded,
  DirectionsWalkRounded,
  EventRounded,
  FaceRounded,
  FavoriteRounded,
  HealthAndSafetyRounded,
  HomeRounded,
  Inventory2Rounded,
  KingBedRounded,
  LocalCafeRounded,
  LuggageRounded,
  MenuBookRounded,
  MonitorHeartRounded,
  SecurityRounded,
  ShoppingBagRounded,
  ShoppingCartRounded,
  ToysRounded,
  VaccinesRounded,
} from '@mui/icons-material';
import type { SvgIconComponent } from '@mui/icons-material';

export const presetIconRegistry: Record<string, SvgIconComponent> = {
  AlarmRounded,
  BadgeRounded,
  BabyChangingStationRounded,
  ChecklistRounded,
  ChildCareRounded,
  DirectionsWalkRounded,
  EventRounded,
  FaceRounded,
  FavoriteRounded,
  HealthAndSafetyRounded,
  HomeRounded,
  Inventory2Rounded,
  KingBedRounded,
  LocalCafeRounded,
  LuggageRounded,
  MenuBookRounded,
  MonitorHeartRounded,
  SecurityRounded,
  ShoppingBagRounded,
  ShoppingCartRounded,
  ToysRounded,
  VaccinesRounded,
};
